version: '3.9'

services:
  php-fpm:
    tty: true
    build:
      context: .
      dockerfile: ./infrastructure/docker/php/Dockerfile
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
      target: dev
    environment:
      COMPOSER_HOME: "/tmp/.composer"
    volumes:
      - "./app:/service/app"
      - "~/.composer:/tmp/.composer"

  nginx:
    build:
      context: .
      dockerfile: ./infrastructure/docker/nginx/Dockerfile
    environment:
      APP_FASTCGI_PASS: 'php-fpm:9000'
    depends_on:
      - php-fpm
    volumes:
      - "./app:/service/app"
    ports:
      - ${WEB_HOST_PORT:-8080}:80
